name: Mark stale issues and pull requests

permissions:
  issues: write
  pull-requests: write
  
on:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-pr-stale: 14
        days-before-pr-close: 365
        stale-pr-label: inactive
        close-pr-label: auto-close
        exempt-pr-labels: keep-open
        stale-pr-message: >
          This pull request has been inactive for 14 days.
          If you are finished with your changes, don't forget to sign off. See the [contributor guide](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-automation?branch=main) for instructions.
          If this PR is inactive for 14 more days, it will be closed automatically. Thank you!
          
          Azure Data Explorer Docs Team
          
          [Contact Us](mailto:kustodocs@microsoft.com)
          
          [Contributor Guide](https://review.docs.microsoft.com/en-us/help/contribute/?branch=main)
        close-pr-message: >
          This pull request has been inactive for 365 days. At this time, we are closing the PR. 
          If you decide to continue working on your change, you can reopen the PR and continue working. Thank you!
           
          Azure Data Explorer Docs Team
          
          [Contact Us](mailto:kustodocs@microsoft.com)
          
          [Contributor Guide](https://review.docs.microsoft.com/en-us/help/contribute/?branch=main)
